require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
  - 'test_prof/rubocop'

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/environments/**/*.rb'
    - 'config/routes.rb'
    - 'config/initializers/*.rb'

Metrics/MethodLength:
  Max: 12

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  SkipBlocks: true

RSpec/ExampleLength:
  Max: 6
  Exclude:
    - 'spec/requests/**/*'

RSpec/AggregateExamples:
  Enabled: true

Rails/Output:
  Exclude:
    - 'lib/v1/data_migrator.rb'
    - 'db/seeds.rb'
    - 'db/seed_data/*.rb'

RSpec/NestedGroups:
  Max: 5

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'
