version: "3.2"
services:
    api:
        build:
            context: ./api
            dockerfile: dev.Dockerfile
            cache_from:
              - better_izivi_api
              - ruby:2.5.1
        container_name: better_izivi_api
        volumes:
            - ./api:/api
        working_dir: /api
        depends_on:
            - mysql
        env_file: 'api/.env.semaphore'
    frontend:
        image: node:10
        container_name: better_izivi_frontend
        volumes:
            - ./frontend:/var/frontend
        working_dir: /var/frontend
    mysql:
        image: mariadb:10.3.14
        container_name: better_izivi_db
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./database:/var/lib/mysql

