default: &default
  rüti:
    name: Regionalzentrum Rüti/ZH
    address:
      primary_line: Vollzugsstelle für den Zivildienst ZIVI
      secondary_line: Regionalzentrum Rüti (ZH)
      street: Spitalstrasse 31
      supplement: Postfach
      city: Rüti
      zip: 8630
  thun:
    name: Regionalzentrum Thun
    address:
      primary_line: Vollzugsstelle für den Zivildienst ZIVI
      secondary_line: Regionalzentrum Thun
      street: Malerweg 6
      city: Thun
      zip: 3600
  aarau:
    name: Regionalzentrum Aarau
    address:
      primary_line: Regionalzentrum Aarau
      secondary_line: Postfach
      street: Bahnhofstrasse 29
      city: Aarau
      zip: 5000
  lausanne:
    name: Regionalzentrum Lausanne
    address:
      primary_line: Centre régional de Lausanne
      secondary_line: Case postale
      street: Route de Chavannes 31
      city: Lausanne
      zip: 1001
  rivera:
    name: Regionalzentrum Rivera
    address:
      primary_line: Centro regionale Rivera
      secondary_line: CP 443
      street: Via Lagacci 8
      city: Rivera
      zip: 6802

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
