#!/bin/bash

jsfiles=$(git diff --cached --name-only --diff-filter=ACM "*.ts" "*.tsx" | sed s,frontend/,,)
phpfiles=$(git diff --cached --name-only --diff-filter=ACM "*.php" | sed s,api/,, | tr '\n' ' ')


exitstatus=0


if [[ ! ( -z "$jsfiles" ) ]];
then
    git checkout-index --prefix=git-export-dir/ -a

    docker run --rm -v $(pwd)/git-export-dir/frontend:/app -w /app node:8 bin/pre-commit "$jsfiles"

    if [[ $? != 0 ]];
    then
        echo
        echo "js files were not properly formatted, please format them with:"
        echo "yarn format"
        echo

        exitstatus=1
    fi
fi



if [[ ! ( -z "$phpfiles" ) ]];
then

    [ ! -d git-export-dir/ ] && git checkout-index --prefix=git-export-dir/ -a
    docker run --rm  -v $(pwd)/git-export-dir/api:/app -v $(pwd)/api/vendor:/app/vendor -w /app izivi_api composer run lint

    if [[ $? -ne 0 ]];
    then
        echo
        echo "php files were not properly formatted, please format them with:"
        echo "composer run format"
        echo "(or run composer install first)"
        echo

        exitstatus=1
    fi
fi

[ -d git-export-dir/ ] && rm -rf git-export-dir/



exit $exitstatus
