 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sys_admin/blog_entries", type: :request do
  # SysAdmin::BlogEntry. As you add validations to SysAdmin::BlogEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SysAdmin::BlogEntry.create! valid_attributes
      get sys_admin_blog_entries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      blog_entry = SysAdmin::BlogEntry.create! valid_attributes
      get sys_admin_blog_entry_path(blog_entry)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_sys_admins_blog_entry_path
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      blog_entry = SysAdmin::BlogEntry.create! valid_attributes
      get edit_blog_entry_url(blog_entry)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SysAdmin::BlogEntry" do
        expect {
          post sys_admin_blog_entries_url, params: { blog_entry: valid_attributes }
        }.to change(SysAdmin::BlogEntry, :count).by(1)
      end

      it "redirects to the created blog_entry" do
        post sys_admin_blog_entries_url, params: { blog_entry: valid_attributes }
        expect(response).to redirect_to(blog_entry_url(@blog_entry))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SysAdmin::BlogEntry" do
        expect {
          post sys_admin_blog_entries_url, params: { blog_entry: invalid_attributes }
        }.to change(SysAdmin::BlogEntry, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post sys_admin_blog_entries_url, params: { blog_entry: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested blog_entry" do
        blog_entry = SysAdmin::BlogEntry.create! valid_attributes
        patch blog_entry_url(blog_entry), params: { blog_entry: new_attributes }
        blog_entry.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the blog_entry" do
        blog_entry = SysAdmin::BlogEntry.create! valid_attributes
        patch blog_entry_url(blog_entry), params: { blog_entry: new_attributes }
        blog_entry.reload
        expect(response).to redirect_to(blog_entry_url(blog_entry))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        blog_entry = SysAdmin::BlogEntry.create! valid_attributes
        patch blog_entry_url(blog_entry), params: { blog_entry: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested blog_entry" do
      blog_entry = SysAdmin::BlogEntry.create! valid_attributes
      expect {
        delete blog_entry_url(blog_entry)
      }.to change(SysAdmin::BlogEntry, :count).by(-1)
    end

    it "redirects to the sys_admin_blog_entries list" do
      blog_entry = SysAdmin::BlogEntry.create! valid_attributes
      delete blog_entry_url(blog_entry)
      expect(response).to redirect_to(sys_admin_blog_entries_url)
    end
  end
end
