# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/organizations/service_specifications', type: :request do
  # ServiceSpecification. As you add validations to ServiceSpecification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      ServiceSpecification.create! valid_attributes
      get organizations_service_specifications_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      service_specification = ServiceSpecification.create! valid_attributes
      get organizations_service_specification_url(organizations_service_specification)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_organizations_service_specification_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      service_specification = ServiceSpecification.create! valid_attributes
      get edit_organizations_service_specification_url(organizations_service_specification)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new ServiceSpecification' do
        expect do
          post organizations_service_specifications_url, params: { organizations_service_specification: valid_attributes }
        end.to change(ServiceSpecification, :count).by(1)
      end

      it 'redirects to the created organizations_service_specification' do
        post organizations_service_specifications_url, params: { organizations_service_specification: valid_attributes }
        expect(response).to redirect_to(organizations_service_specification_url(@organizations_service_specification))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new ServiceSpecification' do
        expect do
          post organizations_service_specifications_url, params: { organizations_service_specification: invalid_attributes }
        end.to change(ServiceSpecification, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post organizations_service_specifications_url, params: { organizations_service_specification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested organizations_service_specification' do
        service_specification = ServiceSpecification.create! valid_attributes
        patch organizations_service_specification_url(organizations_service_specification), params: { organizations_service_specification: new_attributes }
        service_specification.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the organizations_service_specification' do
        service_specification = ServiceSpecification.create! valid_attributes
        patch organizations_service_specification_url(organizations_service_specification), params: { organizations_service_specification: new_attributes }
        service_specification.reload
        expect(response).to redirect_to(organizations_service_specification_url(service_specification))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        service_specification = ServiceSpecification.create! valid_attributes
        patch organizations_service_specification_url(organizations_service_specification), params: { organizations_service_specification: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested organizations_service_specification' do
      service_specification = ServiceSpecification.create! valid_attributes
      expect do
        delete organizations_service_specification_url(organizations_service_specification)
      end.to change(ServiceSpecification, :count).by(-1)
    end

    it 'redirects to the organizations_service_specifications list' do
      service_specification = ServiceSpecification.create! valid_attributes
      delete organizations_service_specification_url(organizations_service_specification)
      expect(response).to redirect_to(organizations_service_specifications_url)
    end
  end
end
