default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '' } %>

development:
  <<: *default
  database: better_izivi_development
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: better_izivi_test
  socket: /tmp/mysql.sock

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
