default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myzivi_development

test:
  <<: *default
  database: myzivi_test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'myzivi_production') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'myzivi') %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
