require:
  - rubocop-rspec

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/NonNilCheck:
  IncludeSemanticChanges: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/environments/**/*.rb'
    - 'config/routes.rb'
    - 'lib/tasks/v1_migration.rake'

Metrics/MethodLength:
  Max: 12

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  SkipBlocks: true

RSpec/ExampleLength:
  Exclude:
    - 'spec/requests/**/*'

RSpec/NestedGroups:
  Max: 5

Rails/Output:
  Exclude:
    - 'lib/v1/data_migrator.rb'

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
