# frozen_string_literal: true

source 'https://rubygems.org'

ruby '2.6.6'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'bootsnap', '>= 1.1.0', require: false
gem 'devise'
gem 'devise-jwt', '~> 0.6.0'
gem 'dotenv-rails'
gem 'fillable-pdf'
gem 'hexapdf'
gem 'iban-tools'
gem 'jbuilder'
gem 'pdf-forms'
gem 'pg'
gem 'prawn'
gem 'prawn-table'
gem 'puma', '~> 3.12'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '~> 6.0.2.2'
gem 'rails-i18n'
gem 'sepa_king'
gem 'validates_timeliness'

group :production do
  gem 'lograge'
  gem 'sentry-raven'
end

group :development, :test do
  gem 'brakeman', require: false
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'debase'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'reek', '~> 6.0.1'
  gem 'rspec-collection_matchers'
  gem 'rspec-rails'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails'
  gem 'rubocop-rspec', require: false
  gem 'ruby-debug-ide'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'letter_opener'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'climate_control'
  gem 'i18n-tasks', '~> 0.9.29'
  gem 'pdf-inspector', require: 'pdf/inspector'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'test-prof'
end

gem 'tzinfo-data'
