name: Lint Code Base

on:
  pull_request:
    branches: [develop, master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          RUBY_LINTER_RULES: .rubocop.yml
          VALIDATE_SQL: false
          JAVASCRIPT_ES_LINTER_RULES: .eslintrc.js
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
